
/*
  Simple Pix Payload Generator (BR Code - EMV QRCPS)
  Based on BCB Specifications
*/

function crc16ccitt(str) {
  let crc = 0xFFFF;
  for (let c = 0; c < str.length; c++) {
    crc ^= str.charCodeAt(c) << 8;
    for (let i = 0; i < 8; i++) {
      if (crc & 0x8000) crc = (crc << 1) ^ 0x1021;
      else crc = crc << 1;
    }
  }
  let hex = (crc & 0xFFFF).toString(16).toUpperCase();
  if (hex.length < 4) hex = '0'.repeat(4 - hex.length) + hex;
  return hex;
}

function formatField(id, value) {
  const len = value.length.toString().padStart(2, '0');
  return `${id}${len}${value}`;
}

export function generatePixPayload({
  key,
  name = 'LAVA JATO TA NOVO',
  city = 'SAO PAULO',
  amount,
  txid = '***' // '***' means auto-generated by PSP or non-specific
}) {
  const cleanedKey = key.replace(/\s/g, '');

  if (!cleanedKey) return null;

  const payload = [
    formatField('00', '01'), // Payload Format Indicator
    formatField('26', [ // Merchant Account Information
      formatField('00', 'BR.GOV.BCB.PIX'),
      formatField('01', cleanedKey)
    ].join('')),
    formatField('52', '0000'), // Merchant Category Code
    formatField('53', '986'), // Transaction Currency (BRL)
    amount ? formatField('54', amount.toFixed(2)) : '', // Transaction Amount
    formatField('58', 'BR'), // Country Code
    formatField('59', name.substring(0, 25).toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")), // Merchant Name
    formatField('60', city.substring(0, 15).toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "")), // Merchant City
    formatField('62', [ // Additional Data Field Template
      formatField('05', txid)
    ].join(''))
  ].join('');

  return `${payload}6304${crc16ccitt(`${payload}6304`)}`;
}
